import type { Metadata } from "next";

// import localFont from "next/font/local";
import "@/app/globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div
        className="flex flex-col min-h-screen bg-cover bg-center"
        style={{ backgroundImage: "url('/images/bg-mainpage.jpg')" }}
      >
        <p>Shop Navbar</p>
        <div className="flex-grow">{children}</div>
      </div>
    </>
  );
}
